---



#Messages

#Sorry for my English, I'm from Russia

error_missing_world: Error missing world!
touch_spawn_point: Touch the spawn point!
touch_sign: Touch the sign to register arena!
game_started: You cannot join!
timer_start: The game start in
game_start_1: Game start!
game_start_2: Have fun!
victory: §l§7> §aYou Win§7< \n §7> §e+§625$ §7 <
time_is_over: §7§l> §6The time is over§7 <
player_count: {COUNT} players remaining

#settings
money-reward: 25

...
